---
- name:  101-internet-access list
  hosts: n9k-1
  connection: local
  gather_facts: no
  tasks:
    - name: obtain login credentials
      include_vars: credentials.yml

    - nxos_config:
        lines:
          - 5 permit ip 10.132.243.9/32 any
          - 10 permit ip 10.241.16.91/32 any
          - 20 permit ip 140.84.159.66/32 any
          - 30 permit ip 140.84.54.128/26 any
          - 240 deny ip any any
        parents: ip access-list 101-internet-access
        before: ip access-list 101-internet-access
        match: exact
        provider: "{{ creds }}"
