---
- name: ping testing
  hosts: n9k-1
  connection: local
  gather_facts: no
  tasks:
    - name: obtain login credentials
      include_vars: credentials.yml

    # test reachability to 8.8.8.8 using mgmt vrf
    - nxos_ping: dest=192.168.99.100 vrf=management host={{ inventory_hostname }} provider="{{ creds }}"

    # Test reachability to a few different public IPs using mgmt vrf
    # if device has name lookups turned on, you can use names
    # - nxos_ping: dest={{ item }} vrf=management  provider="{{ creds }}" host={{ inventory_hostname }}
    #   with_items:
    #     - 8.8.8.8
    #     - 4.4.4.4
